### ISSUE TITLE
It's not open source

### ISSUE THREAD

**Issue by marcin-serwin** [LukeWood/bulletz.io#1]
In `README.md` it is asserted several times that this project is open source, however, this project uses custom license that does not qualify as open source (see the [official definition](https://opensource.org/osd) by OSI). This is misleading. Could you change the term "open source" to "[source available](https://en.wikipedia.org/wiki/Source-available_software)" to avoid confusion?

**Comment by LukeWood** [comment]
Yes absolutely, sorry for the confusion!

**Comment by LukeWood** [comment]
Thanks!  Done
